/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adminLogin;

import static org.hamcrest.Matchers.equalTo;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

import org.testng.annotations.Test;

import io.restassured.http.ContentType;
import utils.MessageConstants;
import utils.Utils;

public class Login {
	Utils util = new Utils();
	Properties properties = new Properties();
	MessageConstants Messages = new MessageConstants();

	public String[] getBaseURI() throws IOException {
		FileInputStream fis = new FileInputStream(System.getProperty("user.dir") + "//env.properties");
		properties.load(fis);
		String ar[] = new String[2];
		ar[0] = properties.getProperty("SUPERADMIN");
		ar[1] = properties.getProperty("ADMIN_PASSWORD");
		return ar;
	}

	@Test
	public void checkIfServerIsUp() throws IOException {
		util.serverIsrunning();
	}

	@Test
	public void superadminLogin() throws IOException {
		String adminCredentialsString[] = getBaseURI();
		util.commonLoginmethods(adminCredentialsString[0], adminCredentialsString[1]).then().assertThat()
				.statusCode(200).and().statusLine(Messages.HTTPSUCCESS_STRING).and().contentType(ContentType.JSON).and()
				.body("description", equalTo("Authentication successful"));

	}
}
